---
"":
  - type: A
    values:
      - 185.199.108.153
      - 185.199.109.153
      - 185.199.110.153
      - 185.199.111.153
  - type: TXT
    values:
      - v=spf1 -all
  - type: MX
    values:
      - exchange: mail.hrntknr.net.
        preference: 10
_dmarc:
  type: TXT
  values:
    - v=DMARC1\; p=reject\; pct=100\; adkim=s\; aspf=s\; rua=mailto:dmarc-rua@hrntknr.net\; ruf=mailto:dmarc-ruf@hrntknr.net\;
mail:
  type: A
  values:
    - 153.217.203.20
mc:
  type: A
  values:
    - 153.217.203.20

cpu:
  - type: CNAME
    value: cpu.hirano.work.
ve1:
  - type: CNAME
    value: ve1.hirano.work.
epg:
  - type: CNAME
    value: epg.hirano.work.
gw.k8s:
  - type: CNAME
    value: gw.k8s.hirano.work.
master.k8s:
  - type: CNAME
    value: master.k8s.hirano.work.

pve1:
  - type: A
    values:
      - 10.196.0.10
sw1:
  - type: A
    values:
      - 10.196.0.12
media:
  - type: A
    values:
      - 10.196.0.20


master1.k8s:
  - type: A
    values:
      - 10.5.0.11
master2.k8s:
  - type: A
    values:
      - 10.5.0.12
master3.k8s:
  - type: A
    values:
      - 10.5.0.13

ts.cpu:
  - type: A
    values:
      - 100.104.115.59
ts.ve1:
  - type: A
    values:
      - 100.72.2.80
ts.jiji:
  - type: A
    values:
      - 100.92.30.109
ts.jerry:
  - type: A
    values:
      - 100.97.87.11
