---
"":
  - type: A
    values:
      - 185.199.108.153
      - 185.199.109.153
      - 185.199.110.153
      - 185.199.111.153
  - type: TXT
    values:
      - v=spf1 -all
  - type: MX
    values:
      - exchange: mail.hrntknr.net.
        preference: 10
_dmarc:
  type: TXT
  values:
    - v=DMARC1\; p=reject\; pct=100\; adkim=s\; aspf=s\; rua=mailto:dmarc-rua@hrntknr.net\; ruf=mailto:dmarc-ruf@hrntknr.net\;
mail:
  type: A
  values:
    - 153.217.203.20
mc:
  type: A
  values:
    - 153.217.203.20

pve1:
  - type: A
    values:
      - 10.196.0.10
sw1:
  - type: A
    values:
      - 10.196.0.12

cpu:
  - type: A
    values:
      - 10.0.0.39
ve1:
  - type: A
    values:
      - 10.0.0.65

ts.cpu:
  - type: A
    values:
      - 100.104.115.59
ts.ve1:
  - type: A
    values:
      - 100.72.2.80
ts.jiji:
  - type: A
    values:
      - 100.92.30.109
ts.jerry:
  - type: A
    values:
      - 100.97.87.11
