---
"":
  - type: A
    values:
      - 185.199.108.153
      - 185.199.109.153
      - 185.199.110.153
      - 185.199.111.153
  - type: TXT
    values:
      - v=spf1 -all
  - type: MX
    values:
      - exchange: 114.164.110.141
        preference: 10

actions:
  type: CNAME
  value: cos.hrntknr.net.

jiji:
  type: A
  values:
    - 10.196.36.2
fou:
  type: A
  values:
    - 10.196.36.3
sh1:
  type: A
  values:
    - 10.196.36.4
cpu:
  type: A
  values:
    - 10.196.36.5
cos:
  type: A
  values:
    - 34.123.133.66
